name: Deploy snowflake-events-monitoring

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve \
          -var "snowflake_account=${{ secrets.SNOWFLAKE_ACCOUNT }}" \
          -var "snowflake_user=${{ secrets.SNOWFLAKE_USER }}" \
          -var "snowflake_password=${{ secrets.SNOWFLAKE_PASSWORD }}" \
          -var "snowflake_warehouse=${{ secrets.SNOWFLAKE_WAREHOUSE }}" \
          -var "snowflake_database=${{ secrets.SNOWFLAKE_DATABASE }}" \
          -var "snowflake_schema=${{ secrets.SNOWFLAKE_SCHEMA }}" \
          -var "snowflake_role=${{ secrets.SNOWFLAKE_ROLE }}"

      # 3. Capture Terraform Outputs
      - name: Export Terraform outputs
        id: tf_outputs
        run: |
          terraform -chdir=terraform output -json > tf_outputs.json
          echo "json=$(cat tf_outputs.json)" >> $GITHUB_OUTPUT

      # 4. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 5. Deploy Function Code
      - name: Deploy Function Code
        uses: azure/functions-action@v1
        with:
          app-name: ${{ fromJson(steps.tf_outputs.outputs.json).function_app_name.value }}
          package: ./function